(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var m=function(c){var b=0;return function(){return b<c.length?{done:!1,value:c[b++]}:{done:!0}}},q=function(c){var b="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return b?b.call(c):{next:m(c)}},r=function(c){for(var b,d=[];!(b=c.next()).done;)d.push(b.value);return d};var t=function(c){var b=0,d;for(d in c)b++;return b},v=function(c,b){return null!==c&&b in c},w=function(c,b){b in c&&delete c[b]};var x=function(c){c&&c.parentNode&&c.parentNode.removeChild(c)};var z=function(c,b,d,e){var a={l:d,index:e.index,i:e.index};e.h[d]=a;e.g.push(a);e.j[d]=!0;e.index++;d=b[d];for(var g=d.c.length-1;0<=g;g--){var h=d.c[g];v(e.h,h.b)?v(e.j,h.b)&&a.i>e.h[h.b].i&&(x(h.instance.a),d.c.splice(g,1)):z(c,b,h.b,e)}if(a.index==a.i)for(;c=e.g[e.g.length-1],w(e.j,c.l),e.g.pop(),c!=a;);},A=function(c,b){c=q(c.childNodes);for(var d=c.next();!d.done;d=c.next())b.appendChild(d.value.cloneNode(!0))};document.addEventListener("DOMContentLoaded",function B(){document.removeEventListener("DOMContentLoaded",B,!1);var b=document,d={},e;if("content"in document.createElement("template")){var a=b.getElementById("gwd-group-definitions");a&&(e=document.importNode(a.content,!0).querySelectorAll("[data-gwd-group-def]"))}e||(e=b.querySelectorAll("[data-gwd-group-def]"));e=q(e);for(a=e.next();!a.done;a=e.next()){a=a.value;var g=a.getAttribute("data-gwd-group-def");g?d[g]?x(a):d[g]={a:a,c:[]}:x(a)}e=[];a=Array.prototype.slice.call(b.querySelectorAll("[data-gwd-group]"));
if("content"in document.createElement("template")&&b.getElementById("gwd-group-definitions"))for(var h in d)g=Array.prototype.slice.call(d[h].a.querySelectorAll("[data-gwd-group]")),0<g.length&&a.push.apply(a,g instanceof Array?g:r(q(g)));h=q(a);for(a=h.next();!a.done;a=h.next()){a=a.value;g=a.childNodes;for(var l=g.length-1;0<=l;l--)8!=g[l].nodeType&&a.removeChild(g[l]);a={a:a,f:a.getAttribute("data-gwd-group")};if(g=d[a.f]){l=a.a.parentNode;for(var y=!1;l&&l!=b;){var u=l.getAttribute("data-gwd-group-def");
if(u&&d[u]){g.c.push({instance:a,b:u});y=!0;break}l=l.parentNode}y||e.push(a)}else x(a.a)}h={index:0,h:{},g:[],j:{}};for(var n in d)v(h.h,n)||z(b,d,n,h);b={};for(var f in d)b[f]={};for(var p in d)for(n=q(d[p].c),f=n.next();!f.done;f=n.next())f=b[f.value.b],p in f?f[p]++:f[p]=1;p=[];for(var k in b)0==t(b[k])&&(p.push(k),w(b,k));k=q(p);for(f=k.next();!f.done;f=k.next())for(n=d[f.value],h=q(n.c),f=h.next();!f.done;f=h.next())f=f.value,A(n.a,f.instance.a),a=b[f.b],a[f.instance.f]--,0==a[f.instance.f]&&
(w(a,f.instance.f),0==t(a)&&(p.push(f.b),w(b,f.b)));e=q(e);for(k=e.next();!k.done;k=e.next())k=k.value,A(d[k.f].a,k.a)},!1);}).call(this);
