(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var c="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var k={m:!0},l={};try{l.__proto__=k;h=l.m;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var m=g,n=this||self,r=function(a,b){function f(){}f.prototype=b.prototype;a.s=b.prototype;a.prototype=new f;a.prototype.constructor=a;a.u=function(d,e,p){for(var y=Array(arguments.length-2),q=2;q<arguments.length;q++)y[q-2]=arguments[q];return b.prototype[e].apply(d,y)}};function t(a){if(Error.captureStackTrace)Error.captureStackTrace(this,t);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}r(t,Error);t.prototype.name="CustomError";var u=function(a,b){a=a.split("%s");for(var f="",d=a.length-1,e=0;e<d;e++)f+=a[e]+(e<b.length?b[e]:"%s");t.call(this,f+a[d])};r(u,t);u.prototype.name="AssertionError";var v=function(a,b,f){if(!a){var d="Assertion failed";if(b){d+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new u(""+d,e||[]);}return a},w=function(a,b){throw new u("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var A=function(a,b){this.c=a===x&&b||"";this.l=z};A.prototype.g=!0;A.prototype.f=function(){return this.c};A.prototype.toString=function(){return"Const{"+this.c+"}"};var z={},x={};var B=new A(x,"_newtab");var D=function(a,b){this.b=b===C?a:""};D.prototype.g=!0;D.prototype.f=function(){return this.b.toString()};D.prototype.toString=function(){return"SafeUrl{"+this.b+"}"};var E=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,C={};var F=function(){var a=HTMLElement.call(this)||this;a.h=!1;a.j=a.o.bind(a);a.i=null;return a},G=HTMLElement;F.prototype=c(G.prototype);F.prototype.constructor=F;if(m)m(F,G);else for(var H in G)if("prototype"!=H)if(Object.defineProperties){var I=Object.getOwnPropertyDescriptor(G,H);I&&Object.defineProperty(F,H,I)}else F[H]=G[H];F.s=G.prototype;
F.prototype.connectedCallback=function(){var a=this;this.h||(document.body.style.opacity="0");setTimeout(function(){a.a=a.querySelector("gwd-pagedeck");window.addEventListener("resize",a.j,!1)},0)};F.prototype.disconnectedCallback=function(){window.removeEventListener("resize",this.j,!1)};F.prototype.initAd=function(){this.h=!0;document.body.style.opacity="";var a=void 0===a?null:a;var b=document.createEvent("CustomEvent");b.initCustomEvent("adinitialized",!0,!0,a);this.dispatchEvent(b);this.goToPage()};
F.prototype.goToPage=function(a,b,f,d,e){if(a=void 0!=a?this.a.getPage(a):this.a.getDefaultPage())a=this.a.getOrientationSpecificPage(window.innerHeight>=window.innerWidth?1:2,a.id),void 0!=b?this.a.goToPage(a.id,b,f,d,e):this.a.goToPage(a.id)};F.prototype.o=function(){var a=window.innerHeight>=window.innerWidth?1:2;this.i!=a&&(this.i=a,(a=this.a.getPage(Number(this.a.currentIndex)))&&this.goToPage(a.id))};
F.prototype.exit=function(a,b,f){b=void 0===b?!1:b;a instanceof D||a instanceof D||(a="object"==typeof a&&a.g?a.f():String(a),v(E.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new D(a,C));if(B instanceof A)if(B instanceof A&&B.constructor===A&&B.l===z)var d=B.c;else w("expected object of type Const, got '"+B+"'"),d="type_error:Const";else d=B||"";var e=n.open;if(a instanceof D&&a.constructor===D)a=a.b;else{var p=typeof a;w("expected object of type SafeUrl, got '"+
a+"' of type "+("object"!=p?p:a?Array.isArray(a)?"array":p:"null"));a="type_error:SafeUrl"}e.call(n,a,d);b&&this.goToPage(f)};customElements.define("gwd-genericad",F);}).call(this);
