(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var d,f=this||self;var h=function(a){this.c="";this.a=[];this.b="";a&&("string"==typeof a?this.h(a):this.g(a))};d=h.prototype;d.i=function(a){for(var b=this.c==a.c&&this.b==a.b&&this.a.length==a.a.length,c=0;b&&c<this.a.length;c++)b=this.a[c]==a.a[c];return b};d.u=function(){return""==this.f()};d.clear=function(){this.c="";this.a=[];this.b=""};
d.g=function(a){this.clear();if(!a)return!1;var b=a.getAttribute("data-gwd-group-def")||"",c=b?[]:[a];for(a=a.parentElement;a&&!b;)a.hasAttribute("data-gwd-group")?c.push(a):b=a.getAttribute("data-gwd-group-def"),a=a.parentElement;c=c.reverse();a=!!b;var g=c[0];if(!a&&!g.id)return!1;for(var e=[],m=a?0:1;m<c.length;m++){var n=c[m].getAttribute("data-gwd-grp-id");if(!n)return!1;e.push(n)}this.c=a?"":g.id;this.a=e;this.b=b||"";return!0};
d.h=function(a){this.clear();a=a.split(" ");for(var b=""==a[0],c="",g=[],e=b?1:0;e<a.length;e++)if(a[e])c?g.push(a[e]):c=a[e];else return!1;if(!c)return!1;b?this.b=c:this.c=c;this.a=g;return!0};
d.j=function(a){if(this.b)var b=a.querySelector('[data-gwd-group-def="'+this.b+'"]');else if(this.c){if(b=a.getElementById(this.c),!b){var c=a.querySelector("gwd-pagedeck");c?"function"==typeof c.getElementById&&(b=c.getElementById(this.c)):"document.body"==this.c&&(b=a.body)}}else return null;return k(this,b)};d.l=function(a,b){if(!this.b)return null;for(a=b;a;){var c=a.getAttribute("data-gwd-group");if(c==this.b)break;a=c&&a!=b?null:a.parentElement}return a?k(this,a):null};
d.f=function(){var a="";this.b?a=" "+this.b:this.c&&(a=this.c);for(var b=0;b<this.a.length;b++)a+=" "+this.a[b];return a};d.o=function(){return this.c};d.s=function(){return this.a};d.m=function(){return this.b};var k=function(a,b){for(var c=0;b&&c<a.a.length;c++){for(var g=b.querySelector('[data-gwd-grp-id="'+a.a[c]+'"]'),e=g?g.parentElement:null;g&&e&&e!=b;)e.hasAttribute("data-gwd-group")?g=null:e=e.parentElement;b=g}return b};var l=["gwd","GwdId"],p=f;l[0]in p||"undefined"==typeof p.execScript||p.execScript("var "+l[0]);for(var q;l.length&&(q=l.shift());)l.length||void 0===h?p=p[q]&&p[q]!==Object.prototype[q]?p[q]:p[q]={}:p[q]=h;h.GROUP_REFERENCE_ATTR="data-gwd-group";h.prototype.equals=h.prototype.i;h.prototype.clear=h.prototype.clear;h.prototype.isEmpty=h.prototype.u;h.prototype.setFromElement=h.prototype.g;h.prototype.setFromString=h.prototype.h;h.prototype.getElement=h.prototype.j;
h.prototype.getElementInInstance=h.prototype.l;h.prototype.getString=h.prototype.f;h.prototype.getLeadingId=h.prototype.o;h.prototype.getPseudoIds=h.prototype.s;h.prototype.getGroupName=h.prototype.m;}).call(this);
